import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { prisma } from '~/lib/prisma'
import { requireClientAuth } from '~/lib/auth.server'
import ReactPDF from '@react-pdf/renderer'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import React from 'react'

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10 },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 12, color: '#666', marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontFamily: 'Helvetica-Bold', marginTop: 16, marginBottom: 8 },
  item: { marginBottom: 8, padding: 8, backgroundColor: '#f8f8f8', borderRadius: 4 },
  itemTitle: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  itemMeta: { fontSize: 9, color: '#666' },
  itemDesc: { fontSize: 9, color: '#444', marginTop: 4 },
  releaseHeader: { marginTop: 12, marginBottom: 6, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: '#ddd' },
  releaseName: { fontSize: 13, fontFamily: 'Helvetica-Bold' },
  releaseMeta: { fontSize: 9, color: '#666', marginTop: 2 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', textAlign: 'center' },
})

export const exportRoadmapPdf = createServerFn({ method: 'GET' })
  .inputValidator(z.object({ roadmapId: z.string() }))
  .handler(async ({ data }) => {
    const { clientId } = await requireClientAuth()

    const roadmap = await prisma.roadmap.findFirst({
      where: { id: data.roadmapId, clientId },
      include: {
        product: { select: { name: true } },
        releases: {
          orderBy: { targetDate: 'asc' },
          include: {
            items: { orderBy: { priority: 'asc' } },
          },
        },
        items: {
          where: { releaseId: null },
          orderBy: { priority: 'asc' },
        },
      },
    })
    if (!roadmap) throw new Error('Roadmap not found')

    const doc = React.createElement(
      Document,
      null,
      React.createElement(
        Page,
        { size: 'A4', style: styles.page },
        React.createElement(Text, { style: styles.title }, roadmap.name),
        React.createElement(
          Text,
          { style: styles.subtitle },
          `${roadmap.product.name}${roadmap.description ? ` — ${roadmap.description}` : ''}`,
        ),

        // Releases with items
        ...roadmap.releases.map((release) =>
          React.createElement(
            View,
            { key: release.id },
            React.createElement(
              View,
              { style: styles.releaseHeader },
              React.createElement(Text, { style: styles.releaseName }, release.name),
              React.createElement(
                Text,
                { style: styles.releaseMeta },
                `${release.status}${release.targetDate ? ` • Target: ${release.targetDate.toISOString().split('T')[0]}` : ''}`,
              ),
            ),
            ...release.items.map((item) =>
              React.createElement(
                View,
                { key: item.id, style: styles.item },
                React.createElement(Text, { style: styles.itemTitle }, item.title),
                React.createElement(
                  Text,
                  { style: styles.itemMeta },
                  `Status: ${item.status}${item.startDate ? ` • Start: ${item.startDate.toISOString().split('T')[0]}` : ''}${item.endDate ? ` • End: ${item.endDate.toISOString().split('T')[0]}` : ''}`,
                ),
                item.description
                  ? React.createElement(Text, { style: styles.itemDesc }, item.description)
                  : null,
              ),
            ),
          ),
        ),

        // Unassigned items
        ...(roadmap.items.length > 0
          ? [
              React.createElement(
                View,
                { key: 'unassigned' },
                React.createElement(Text, { style: styles.sectionTitle }, 'Backlog (No Release)'),
                ...roadmap.items.map((item) =>
                  React.createElement(
                    View,
                    { key: item.id, style: styles.item },
                    React.createElement(Text, { style: styles.itemTitle }, item.title),
                    React.createElement(Text, { style: styles.itemMeta }, `Status: ${item.status}`),
                    item.description
                      ? React.createElement(Text, { style: styles.itemDesc }, item.description)
                      : null,
                  ),
                ),
              ),
            ]
          : []),

        React.createElement(
          Text,
          { style: styles.footer },
          `Generated by ProductPlan on ${new Date().toISOString().split('T')[0]}`,
        ),
      ),
    )

    const buffer = await ReactPDF.renderToBuffer(doc)
    const base64 = Buffer.from(buffer).toString('base64')

    const slug = roadmap.name.toLowerCase().replace(/\s+/g, '-')
    return { base64, filename: `roadmap-${slug}.pdf` }
  })
