/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSuperAdminRouteImport } from './routes/_authed/super-admin'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedOrgSlugRouteImport } from './routes/_authed/$orgSlug'
import { Route as AuthedOrgSlugIndexRouteImport } from './routes/_authed/$orgSlug/index'
import { Route as AuthedSuperAdminLoginRouteImport } from './routes/_authed/super-admin/login'
import { Route as AuthedOrgSlugSettingsRouteImport } from './routes/_authed/$orgSlug/settings'
import { Route as AuthedOrgSlugProductsRouteImport } from './routes/_authed/$orgSlug/products'
import { Route as AuthedSuperAdminClientsIndexRouteImport } from './routes/_authed/super-admin/clients/index'
import { Route as AuthedOrgSlugProductsIndexRouteImport } from './routes/_authed/$orgSlug/products.index'
import { Route as AuthedSuperAdminClientsClientIdRouteImport } from './routes/_authed/super-admin/clients/$clientId'
import { Route as AuthedOrgSlugProductsNewRouteImport } from './routes/_authed/$orgSlug/products.new'
import { Route as AuthedOrgSlugProductsProductIdRouteImport } from './routes/_authed/$orgSlug/products.$productId'
import { Route as AuthedOrgSlugProductsProductIdRoadmapRouteImport } from './routes/_authed/$orgSlug/products.$productId.roadmap'
import { Route as AuthedOrgSlugProductsProductIdReleasesRouteImport } from './routes/_authed/$orgSlug/products.$productId.releases'
import { Route as AuthedOrgSlugProductsProductIdIssuesRouteImport } from './routes/_authed/$orgSlug/products.$productId.issues'
import { Route as AuthedOrgSlugProductsProductIdIdeasRouteImport } from './routes/_authed/$orgSlug/products.$productId.ideas'
import { Route as AuthedOrgSlugProductsProductIdGoalsRouteImport } from './routes/_authed/$orgSlug/products.$productId.goals'
import { Route as AuthedOrgSlugProductsProductIdFeaturesRouteImport } from './routes/_authed/$orgSlug/products.$productId.features'
import { Route as AuthedOrgSlugProductsProductIdActionsRouteImport } from './routes/_authed/$orgSlug/products.$productId.actions'
import { Route as AuthedOrgSlugProductsProductIdRoadmapIndexRouteImport } from './routes/_authed/$orgSlug/products.$productId.roadmap.index'
import { Route as AuthedOrgSlugProductsProductIdIssuesIndexRouteImport } from './routes/_authed/$orgSlug/products.$productId.issues.index'
import { Route as AuthedOrgSlugProductsProductIdIdeasIndexRouteImport } from './routes/_authed/$orgSlug/products.$productId.ideas.index'
import { Route as AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRouteImport } from './routes/_authed/$orgSlug/products.$productId.roadmap.$roadmapId'
import { Route as AuthedOrgSlugProductsProductIdIssuesIssueIdRouteImport } from './routes/_authed/$orgSlug/products.$productId.issues.$issueId'
import { Route as AuthedOrgSlugProductsProductIdIdeasIdeaIdRouteImport } from './routes/_authed/$orgSlug/products.$productId.ideas.$ideaId'
import { Route as AuthedOrgSlugProductsProductIdFeaturesFeatureIdRouteImport } from './routes/_authed/$orgSlug/products.$productId.features.$featureId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSuperAdminRoute = AuthedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSlugRoute = AuthedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgSlugIndexRoute = AuthedOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedSuperAdminLoginRoute = AuthedSuperAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthedSuperAdminRoute,
} as any)
const AuthedOrgSlugSettingsRoute = AuthedOrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedOrgSlugProductsRoute = AuthedOrgSlugProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedOrgSlugRoute,
} as any)
const AuthedSuperAdminClientsIndexRoute =
  AuthedSuperAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthedSuperAdminRoute,
  } as any)
const AuthedOrgSlugProductsIndexRoute =
  AuthedOrgSlugProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgSlugProductsRoute,
  } as any)
const AuthedSuperAdminClientsClientIdRoute =
  AuthedSuperAdminClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthedSuperAdminRoute,
  } as any)
const AuthedOrgSlugProductsNewRoute =
  AuthedOrgSlugProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedOrgSlugProductsRoute,
  } as any)
const AuthedOrgSlugProductsProductIdRoute =
  AuthedOrgSlugProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthedOrgSlugProductsRoute,
  } as any)
const AuthedOrgSlugProductsProductIdRoadmapRoute =
  AuthedOrgSlugProductsProductIdRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdReleasesRoute =
  AuthedOrgSlugProductsProductIdReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdIssuesRoute =
  AuthedOrgSlugProductsProductIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdIdeasRoute =
  AuthedOrgSlugProductsProductIdIdeasRouteImport.update({
    id: '/ideas',
    path: '/ideas',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdGoalsRoute =
  AuthedOrgSlugProductsProductIdGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdFeaturesRoute =
  AuthedOrgSlugProductsProductIdFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdActionsRoute =
  AuthedOrgSlugProductsProductIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoute,
  } as any)
const AuthedOrgSlugProductsProductIdRoadmapIndexRoute =
  AuthedOrgSlugProductsProductIdRoadmapIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoadmapRoute,
  } as any)
const AuthedOrgSlugProductsProductIdIssuesIndexRoute =
  AuthedOrgSlugProductsProductIdIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgSlugProductsProductIdIssuesRoute,
  } as any)
const AuthedOrgSlugProductsProductIdIdeasIndexRoute =
  AuthedOrgSlugProductsProductIdIdeasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgSlugProductsProductIdIdeasRoute,
  } as any)
const AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute =
  AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRouteImport.update({
    id: '/$roadmapId',
    path: '/$roadmapId',
    getParentRoute: () => AuthedOrgSlugProductsProductIdRoadmapRoute,
  } as any)
const AuthedOrgSlugProductsProductIdIssuesIssueIdRoute =
  AuthedOrgSlugProductsProductIdIssuesIssueIdRouteImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => AuthedOrgSlugProductsProductIdIssuesRoute,
  } as any)
const AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute =
  AuthedOrgSlugProductsProductIdIdeasIdeaIdRouteImport.update({
    id: '/$ideaId',
    path: '/$ideaId',
    getParentRoute: () => AuthedOrgSlugProductsProductIdIdeasRoute,
  } as any)
const AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute =
  AuthedOrgSlugProductsProductIdFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => AuthedOrgSlugProductsProductIdFeaturesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof AuthedOrgSlugRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/super-admin': typeof AuthedSuperAdminRouteWithChildren
  '/$orgSlug/products': typeof AuthedOrgSlugProductsRouteWithChildren
  '/$orgSlug/settings': typeof AuthedOrgSlugSettingsRoute
  '/super-admin/login': typeof AuthedSuperAdminLoginRoute
  '/$orgSlug/': typeof AuthedOrgSlugIndexRoute
  '/$orgSlug/products/$productId': typeof AuthedOrgSlugProductsProductIdRouteWithChildren
  '/$orgSlug/products/new': typeof AuthedOrgSlugProductsNewRoute
  '/super-admin/clients/$clientId': typeof AuthedSuperAdminClientsClientIdRoute
  '/$orgSlug/products/': typeof AuthedOrgSlugProductsIndexRoute
  '/super-admin/clients/': typeof AuthedSuperAdminClientsIndexRoute
  '/$orgSlug/products/$productId/actions': typeof AuthedOrgSlugProductsProductIdActionsRoute
  '/$orgSlug/products/$productId/features': typeof AuthedOrgSlugProductsProductIdFeaturesRouteWithChildren
  '/$orgSlug/products/$productId/goals': typeof AuthedOrgSlugProductsProductIdGoalsRoute
  '/$orgSlug/products/$productId/ideas': typeof AuthedOrgSlugProductsProductIdIdeasRouteWithChildren
  '/$orgSlug/products/$productId/issues': typeof AuthedOrgSlugProductsProductIdIssuesRouteWithChildren
  '/$orgSlug/products/$productId/releases': typeof AuthedOrgSlugProductsProductIdReleasesRoute
  '/$orgSlug/products/$productId/roadmap': typeof AuthedOrgSlugProductsProductIdRoadmapRouteWithChildren
  '/$orgSlug/products/$productId/features/$featureId': typeof AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute
  '/$orgSlug/products/$productId/ideas/$ideaId': typeof AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute
  '/$orgSlug/products/$productId/issues/$issueId': typeof AuthedOrgSlugProductsProductIdIssuesIssueIdRoute
  '/$orgSlug/products/$productId/roadmap/$roadmapId': typeof AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute
  '/$orgSlug/products/$productId/ideas/': typeof AuthedOrgSlugProductsProductIdIdeasIndexRoute
  '/$orgSlug/products/$productId/issues/': typeof AuthedOrgSlugProductsProductIdIssuesIndexRoute
  '/$orgSlug/products/$productId/roadmap/': typeof AuthedOrgSlugProductsProductIdRoadmapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/super-admin': typeof AuthedSuperAdminRouteWithChildren
  '/$orgSlug/settings': typeof AuthedOrgSlugSettingsRoute
  '/super-admin/login': typeof AuthedSuperAdminLoginRoute
  '/$orgSlug': typeof AuthedOrgSlugIndexRoute
  '/$orgSlug/products/$productId': typeof AuthedOrgSlugProductsProductIdRouteWithChildren
  '/$orgSlug/products/new': typeof AuthedOrgSlugProductsNewRoute
  '/super-admin/clients/$clientId': typeof AuthedSuperAdminClientsClientIdRoute
  '/$orgSlug/products': typeof AuthedOrgSlugProductsIndexRoute
  '/super-admin/clients': typeof AuthedSuperAdminClientsIndexRoute
  '/$orgSlug/products/$productId/actions': typeof AuthedOrgSlugProductsProductIdActionsRoute
  '/$orgSlug/products/$productId/features': typeof AuthedOrgSlugProductsProductIdFeaturesRouteWithChildren
  '/$orgSlug/products/$productId/goals': typeof AuthedOrgSlugProductsProductIdGoalsRoute
  '/$orgSlug/products/$productId/releases': typeof AuthedOrgSlugProductsProductIdReleasesRoute
  '/$orgSlug/products/$productId/features/$featureId': typeof AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute
  '/$orgSlug/products/$productId/ideas/$ideaId': typeof AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute
  '/$orgSlug/products/$productId/issues/$issueId': typeof AuthedOrgSlugProductsProductIdIssuesIssueIdRoute
  '/$orgSlug/products/$productId/roadmap/$roadmapId': typeof AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute
  '/$orgSlug/products/$productId/ideas': typeof AuthedOrgSlugProductsProductIdIdeasIndexRoute
  '/$orgSlug/products/$productId/issues': typeof AuthedOrgSlugProductsProductIdIssuesIndexRoute
  '/$orgSlug/products/$productId/roadmap': typeof AuthedOrgSlugProductsProductIdRoadmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/$orgSlug': typeof AuthedOrgSlugRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/super-admin': typeof AuthedSuperAdminRouteWithChildren
  '/_authed/$orgSlug/products': typeof AuthedOrgSlugProductsRouteWithChildren
  '/_authed/$orgSlug/settings': typeof AuthedOrgSlugSettingsRoute
  '/_authed/super-admin/login': typeof AuthedSuperAdminLoginRoute
  '/_authed/$orgSlug/': typeof AuthedOrgSlugIndexRoute
  '/_authed/$orgSlug/products/$productId': typeof AuthedOrgSlugProductsProductIdRouteWithChildren
  '/_authed/$orgSlug/products/new': typeof AuthedOrgSlugProductsNewRoute
  '/_authed/super-admin/clients/$clientId': typeof AuthedSuperAdminClientsClientIdRoute
  '/_authed/$orgSlug/products/': typeof AuthedOrgSlugProductsIndexRoute
  '/_authed/super-admin/clients/': typeof AuthedSuperAdminClientsIndexRoute
  '/_authed/$orgSlug/products/$productId/actions': typeof AuthedOrgSlugProductsProductIdActionsRoute
  '/_authed/$orgSlug/products/$productId/features': typeof AuthedOrgSlugProductsProductIdFeaturesRouteWithChildren
  '/_authed/$orgSlug/products/$productId/goals': typeof AuthedOrgSlugProductsProductIdGoalsRoute
  '/_authed/$orgSlug/products/$productId/ideas': typeof AuthedOrgSlugProductsProductIdIdeasRouteWithChildren
  '/_authed/$orgSlug/products/$productId/issues': typeof AuthedOrgSlugProductsProductIdIssuesRouteWithChildren
  '/_authed/$orgSlug/products/$productId/releases': typeof AuthedOrgSlugProductsProductIdReleasesRoute
  '/_authed/$orgSlug/products/$productId/roadmap': typeof AuthedOrgSlugProductsProductIdRoadmapRouteWithChildren
  '/_authed/$orgSlug/products/$productId/features/$featureId': typeof AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute
  '/_authed/$orgSlug/products/$productId/ideas/$ideaId': typeof AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute
  '/_authed/$orgSlug/products/$productId/issues/$issueId': typeof AuthedOrgSlugProductsProductIdIssuesIssueIdRoute
  '/_authed/$orgSlug/products/$productId/roadmap/$roadmapId': typeof AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute
  '/_authed/$orgSlug/products/$productId/ideas/': typeof AuthedOrgSlugProductsProductIdIdeasIndexRoute
  '/_authed/$orgSlug/products/$productId/issues/': typeof AuthedOrgSlugProductsProductIdIssuesIndexRoute
  '/_authed/$orgSlug/products/$productId/roadmap/': typeof AuthedOrgSlugProductsProductIdRoadmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/onboarding'
    | '/super-admin'
    | '/$orgSlug/products'
    | '/$orgSlug/settings'
    | '/super-admin/login'
    | '/$orgSlug/'
    | '/$orgSlug/products/$productId'
    | '/$orgSlug/products/new'
    | '/super-admin/clients/$clientId'
    | '/$orgSlug/products/'
    | '/super-admin/clients/'
    | '/$orgSlug/products/$productId/actions'
    | '/$orgSlug/products/$productId/features'
    | '/$orgSlug/products/$productId/goals'
    | '/$orgSlug/products/$productId/ideas'
    | '/$orgSlug/products/$productId/issues'
    | '/$orgSlug/products/$productId/releases'
    | '/$orgSlug/products/$productId/roadmap'
    | '/$orgSlug/products/$productId/features/$featureId'
    | '/$orgSlug/products/$productId/ideas/$ideaId'
    | '/$orgSlug/products/$productId/issues/$issueId'
    | '/$orgSlug/products/$productId/roadmap/$roadmapId'
    | '/$orgSlug/products/$productId/ideas/'
    | '/$orgSlug/products/$productId/issues/'
    | '/$orgSlug/products/$productId/roadmap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/super-admin'
    | '/$orgSlug/settings'
    | '/super-admin/login'
    | '/$orgSlug'
    | '/$orgSlug/products/$productId'
    | '/$orgSlug/products/new'
    | '/super-admin/clients/$clientId'
    | '/$orgSlug/products'
    | '/super-admin/clients'
    | '/$orgSlug/products/$productId/actions'
    | '/$orgSlug/products/$productId/features'
    | '/$orgSlug/products/$productId/goals'
    | '/$orgSlug/products/$productId/releases'
    | '/$orgSlug/products/$productId/features/$featureId'
    | '/$orgSlug/products/$productId/ideas/$ideaId'
    | '/$orgSlug/products/$productId/issues/$issueId'
    | '/$orgSlug/products/$productId/roadmap/$roadmapId'
    | '/$orgSlug/products/$productId/ideas'
    | '/$orgSlug/products/$productId/issues'
    | '/$orgSlug/products/$productId/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/$orgSlug'
    | '/_authed/onboarding'
    | '/_authed/super-admin'
    | '/_authed/$orgSlug/products'
    | '/_authed/$orgSlug/settings'
    | '/_authed/super-admin/login'
    | '/_authed/$orgSlug/'
    | '/_authed/$orgSlug/products/$productId'
    | '/_authed/$orgSlug/products/new'
    | '/_authed/super-admin/clients/$clientId'
    | '/_authed/$orgSlug/products/'
    | '/_authed/super-admin/clients/'
    | '/_authed/$orgSlug/products/$productId/actions'
    | '/_authed/$orgSlug/products/$productId/features'
    | '/_authed/$orgSlug/products/$productId/goals'
    | '/_authed/$orgSlug/products/$productId/ideas'
    | '/_authed/$orgSlug/products/$productId/issues'
    | '/_authed/$orgSlug/products/$productId/releases'
    | '/_authed/$orgSlug/products/$productId/roadmap'
    | '/_authed/$orgSlug/products/$productId/features/$featureId'
    | '/_authed/$orgSlug/products/$productId/ideas/$ideaId'
    | '/_authed/$orgSlug/products/$productId/issues/$issueId'
    | '/_authed/$orgSlug/products/$productId/roadmap/$roadmapId'
    | '/_authed/$orgSlug/products/$productId/ideas/'
    | '/_authed/$orgSlug/products/$productId/issues/'
    | '/_authed/$orgSlug/products/$productId/roadmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/super-admin': {
      id: '/_authed/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthedSuperAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$orgSlug': {
      id: '/_authed/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthedOrgSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$orgSlug/': {
      id: '/_authed/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/super-admin/login': {
      id: '/_authed/super-admin/login'
      path: '/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof AuthedSuperAdminLoginRouteImport
      parentRoute: typeof AuthedSuperAdminRoute
    }
    '/_authed/$orgSlug/settings': {
      id: '/_authed/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AuthedOrgSlugSettingsRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/$orgSlug/products': {
      id: '/_authed/$orgSlug/products'
      path: '/products'
      fullPath: '/$orgSlug/products'
      preLoaderRoute: typeof AuthedOrgSlugProductsRouteImport
      parentRoute: typeof AuthedOrgSlugRoute
    }
    '/_authed/super-admin/clients/': {
      id: '/_authed/super-admin/clients/'
      path: '/clients'
      fullPath: '/super-admin/clients/'
      preLoaderRoute: typeof AuthedSuperAdminClientsIndexRouteImport
      parentRoute: typeof AuthedSuperAdminRoute
    }
    '/_authed/$orgSlug/products/': {
      id: '/_authed/$orgSlug/products/'
      path: '/'
      fullPath: '/$orgSlug/products/'
      preLoaderRoute: typeof AuthedOrgSlugProductsIndexRouteImport
      parentRoute: typeof AuthedOrgSlugProductsRoute
    }
    '/_authed/super-admin/clients/$clientId': {
      id: '/_authed/super-admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/super-admin/clients/$clientId'
      preLoaderRoute: typeof AuthedSuperAdminClientsClientIdRouteImport
      parentRoute: typeof AuthedSuperAdminRoute
    }
    '/_authed/$orgSlug/products/new': {
      id: '/_authed/$orgSlug/products/new'
      path: '/new'
      fullPath: '/$orgSlug/products/new'
      preLoaderRoute: typeof AuthedOrgSlugProductsNewRouteImport
      parentRoute: typeof AuthedOrgSlugProductsRoute
    }
    '/_authed/$orgSlug/products/$productId': {
      id: '/_authed/$orgSlug/products/$productId'
      path: '/$productId'
      fullPath: '/$orgSlug/products/$productId'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdRouteImport
      parentRoute: typeof AuthedOrgSlugProductsRoute
    }
    '/_authed/$orgSlug/products/$productId/roadmap': {
      id: '/_authed/$orgSlug/products/$productId/roadmap'
      path: '/roadmap'
      fullPath: '/$orgSlug/products/$productId/roadmap'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdRoadmapRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/releases': {
      id: '/_authed/$orgSlug/products/$productId/releases'
      path: '/releases'
      fullPath: '/$orgSlug/products/$productId/releases'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdReleasesRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/issues': {
      id: '/_authed/$orgSlug/products/$productId/issues'
      path: '/issues'
      fullPath: '/$orgSlug/products/$productId/issues'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdIssuesRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/ideas': {
      id: '/_authed/$orgSlug/products/$productId/ideas'
      path: '/ideas'
      fullPath: '/$orgSlug/products/$productId/ideas'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdIdeasRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/goals': {
      id: '/_authed/$orgSlug/products/$productId/goals'
      path: '/goals'
      fullPath: '/$orgSlug/products/$productId/goals'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdGoalsRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/features': {
      id: '/_authed/$orgSlug/products/$productId/features'
      path: '/features'
      fullPath: '/$orgSlug/products/$productId/features'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdFeaturesRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/actions': {
      id: '/_authed/$orgSlug/products/$productId/actions'
      path: '/actions'
      fullPath: '/$orgSlug/products/$productId/actions'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdActionsRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoute
    }
    '/_authed/$orgSlug/products/$productId/roadmap/': {
      id: '/_authed/$orgSlug/products/$productId/roadmap/'
      path: '/'
      fullPath: '/$orgSlug/products/$productId/roadmap/'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdRoadmapIndexRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoadmapRoute
    }
    '/_authed/$orgSlug/products/$productId/issues/': {
      id: '/_authed/$orgSlug/products/$productId/issues/'
      path: '/'
      fullPath: '/$orgSlug/products/$productId/issues/'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdIssuesIndexRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdIssuesRoute
    }
    '/_authed/$orgSlug/products/$productId/ideas/': {
      id: '/_authed/$orgSlug/products/$productId/ideas/'
      path: '/'
      fullPath: '/$orgSlug/products/$productId/ideas/'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdIdeasIndexRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdIdeasRoute
    }
    '/_authed/$orgSlug/products/$productId/roadmap/$roadmapId': {
      id: '/_authed/$orgSlug/products/$productId/roadmap/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/$orgSlug/products/$productId/roadmap/$roadmapId'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdRoadmapRoute
    }
    '/_authed/$orgSlug/products/$productId/issues/$issueId': {
      id: '/_authed/$orgSlug/products/$productId/issues/$issueId'
      path: '/$issueId'
      fullPath: '/$orgSlug/products/$productId/issues/$issueId'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdIssuesIssueIdRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdIssuesRoute
    }
    '/_authed/$orgSlug/products/$productId/ideas/$ideaId': {
      id: '/_authed/$orgSlug/products/$productId/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/$orgSlug/products/$productId/ideas/$ideaId'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdIdeasIdeaIdRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdIdeasRoute
    }
    '/_authed/$orgSlug/products/$productId/features/$featureId': {
      id: '/_authed/$orgSlug/products/$productId/features/$featureId'
      path: '/$featureId'
      fullPath: '/$orgSlug/products/$productId/features/$featureId'
      preLoaderRoute: typeof AuthedOrgSlugProductsProductIdFeaturesFeatureIdRouteImport
      parentRoute: typeof AuthedOrgSlugProductsProductIdFeaturesRoute
    }
  }
}

interface AuthedOrgSlugProductsProductIdFeaturesRouteChildren {
  AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute: typeof AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute
}

const AuthedOrgSlugProductsProductIdFeaturesRouteChildren: AuthedOrgSlugProductsProductIdFeaturesRouteChildren =
  {
    AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute:
      AuthedOrgSlugProductsProductIdFeaturesFeatureIdRoute,
  }

const AuthedOrgSlugProductsProductIdFeaturesRouteWithChildren =
  AuthedOrgSlugProductsProductIdFeaturesRoute._addFileChildren(
    AuthedOrgSlugProductsProductIdFeaturesRouteChildren,
  )

interface AuthedOrgSlugProductsProductIdIdeasRouteChildren {
  AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute: typeof AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute
  AuthedOrgSlugProductsProductIdIdeasIndexRoute: typeof AuthedOrgSlugProductsProductIdIdeasIndexRoute
}

const AuthedOrgSlugProductsProductIdIdeasRouteChildren: AuthedOrgSlugProductsProductIdIdeasRouteChildren =
  {
    AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute:
      AuthedOrgSlugProductsProductIdIdeasIdeaIdRoute,
    AuthedOrgSlugProductsProductIdIdeasIndexRoute:
      AuthedOrgSlugProductsProductIdIdeasIndexRoute,
  }

const AuthedOrgSlugProductsProductIdIdeasRouteWithChildren =
  AuthedOrgSlugProductsProductIdIdeasRoute._addFileChildren(
    AuthedOrgSlugProductsProductIdIdeasRouteChildren,
  )

interface AuthedOrgSlugProductsProductIdIssuesRouteChildren {
  AuthedOrgSlugProductsProductIdIssuesIssueIdRoute: typeof AuthedOrgSlugProductsProductIdIssuesIssueIdRoute
  AuthedOrgSlugProductsProductIdIssuesIndexRoute: typeof AuthedOrgSlugProductsProductIdIssuesIndexRoute
}

const AuthedOrgSlugProductsProductIdIssuesRouteChildren: AuthedOrgSlugProductsProductIdIssuesRouteChildren =
  {
    AuthedOrgSlugProductsProductIdIssuesIssueIdRoute:
      AuthedOrgSlugProductsProductIdIssuesIssueIdRoute,
    AuthedOrgSlugProductsProductIdIssuesIndexRoute:
      AuthedOrgSlugProductsProductIdIssuesIndexRoute,
  }

const AuthedOrgSlugProductsProductIdIssuesRouteWithChildren =
  AuthedOrgSlugProductsProductIdIssuesRoute._addFileChildren(
    AuthedOrgSlugProductsProductIdIssuesRouteChildren,
  )

interface AuthedOrgSlugProductsProductIdRoadmapRouteChildren {
  AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute: typeof AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute
  AuthedOrgSlugProductsProductIdRoadmapIndexRoute: typeof AuthedOrgSlugProductsProductIdRoadmapIndexRoute
}

const AuthedOrgSlugProductsProductIdRoadmapRouteChildren: AuthedOrgSlugProductsProductIdRoadmapRouteChildren =
  {
    AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute:
      AuthedOrgSlugProductsProductIdRoadmapRoadmapIdRoute,
    AuthedOrgSlugProductsProductIdRoadmapIndexRoute:
      AuthedOrgSlugProductsProductIdRoadmapIndexRoute,
  }

const AuthedOrgSlugProductsProductIdRoadmapRouteWithChildren =
  AuthedOrgSlugProductsProductIdRoadmapRoute._addFileChildren(
    AuthedOrgSlugProductsProductIdRoadmapRouteChildren,
  )

interface AuthedOrgSlugProductsProductIdRouteChildren {
  AuthedOrgSlugProductsProductIdActionsRoute: typeof AuthedOrgSlugProductsProductIdActionsRoute
  AuthedOrgSlugProductsProductIdFeaturesRoute: typeof AuthedOrgSlugProductsProductIdFeaturesRouteWithChildren
  AuthedOrgSlugProductsProductIdGoalsRoute: typeof AuthedOrgSlugProductsProductIdGoalsRoute
  AuthedOrgSlugProductsProductIdIdeasRoute: typeof AuthedOrgSlugProductsProductIdIdeasRouteWithChildren
  AuthedOrgSlugProductsProductIdIssuesRoute: typeof AuthedOrgSlugProductsProductIdIssuesRouteWithChildren
  AuthedOrgSlugProductsProductIdReleasesRoute: typeof AuthedOrgSlugProductsProductIdReleasesRoute
  AuthedOrgSlugProductsProductIdRoadmapRoute: typeof AuthedOrgSlugProductsProductIdRoadmapRouteWithChildren
}

const AuthedOrgSlugProductsProductIdRouteChildren: AuthedOrgSlugProductsProductIdRouteChildren =
  {
    AuthedOrgSlugProductsProductIdActionsRoute:
      AuthedOrgSlugProductsProductIdActionsRoute,
    AuthedOrgSlugProductsProductIdFeaturesRoute:
      AuthedOrgSlugProductsProductIdFeaturesRouteWithChildren,
    AuthedOrgSlugProductsProductIdGoalsRoute:
      AuthedOrgSlugProductsProductIdGoalsRoute,
    AuthedOrgSlugProductsProductIdIdeasRoute:
      AuthedOrgSlugProductsProductIdIdeasRouteWithChildren,
    AuthedOrgSlugProductsProductIdIssuesRoute:
      AuthedOrgSlugProductsProductIdIssuesRouteWithChildren,
    AuthedOrgSlugProductsProductIdReleasesRoute:
      AuthedOrgSlugProductsProductIdReleasesRoute,
    AuthedOrgSlugProductsProductIdRoadmapRoute:
      AuthedOrgSlugProductsProductIdRoadmapRouteWithChildren,
  }

const AuthedOrgSlugProductsProductIdRouteWithChildren =
  AuthedOrgSlugProductsProductIdRoute._addFileChildren(
    AuthedOrgSlugProductsProductIdRouteChildren,
  )

interface AuthedOrgSlugProductsRouteChildren {
  AuthedOrgSlugProductsProductIdRoute: typeof AuthedOrgSlugProductsProductIdRouteWithChildren
  AuthedOrgSlugProductsNewRoute: typeof AuthedOrgSlugProductsNewRoute
  AuthedOrgSlugProductsIndexRoute: typeof AuthedOrgSlugProductsIndexRoute
}

const AuthedOrgSlugProductsRouteChildren: AuthedOrgSlugProductsRouteChildren = {
  AuthedOrgSlugProductsProductIdRoute:
    AuthedOrgSlugProductsProductIdRouteWithChildren,
  AuthedOrgSlugProductsNewRoute: AuthedOrgSlugProductsNewRoute,
  AuthedOrgSlugProductsIndexRoute: AuthedOrgSlugProductsIndexRoute,
}

const AuthedOrgSlugProductsRouteWithChildren =
  AuthedOrgSlugProductsRoute._addFileChildren(
    AuthedOrgSlugProductsRouteChildren,
  )

interface AuthedOrgSlugRouteChildren {
  AuthedOrgSlugProductsRoute: typeof AuthedOrgSlugProductsRouteWithChildren
  AuthedOrgSlugSettingsRoute: typeof AuthedOrgSlugSettingsRoute
  AuthedOrgSlugIndexRoute: typeof AuthedOrgSlugIndexRoute
}

const AuthedOrgSlugRouteChildren: AuthedOrgSlugRouteChildren = {
  AuthedOrgSlugProductsRoute: AuthedOrgSlugProductsRouteWithChildren,
  AuthedOrgSlugSettingsRoute: AuthedOrgSlugSettingsRoute,
  AuthedOrgSlugIndexRoute: AuthedOrgSlugIndexRoute,
}

const AuthedOrgSlugRouteWithChildren = AuthedOrgSlugRoute._addFileChildren(
  AuthedOrgSlugRouteChildren,
)

interface AuthedSuperAdminRouteChildren {
  AuthedSuperAdminLoginRoute: typeof AuthedSuperAdminLoginRoute
  AuthedSuperAdminClientsClientIdRoute: typeof AuthedSuperAdminClientsClientIdRoute
  AuthedSuperAdminClientsIndexRoute: typeof AuthedSuperAdminClientsIndexRoute
}

const AuthedSuperAdminRouteChildren: AuthedSuperAdminRouteChildren = {
  AuthedSuperAdminLoginRoute: AuthedSuperAdminLoginRoute,
  AuthedSuperAdminClientsClientIdRoute: AuthedSuperAdminClientsClientIdRoute,
  AuthedSuperAdminClientsIndexRoute: AuthedSuperAdminClientsIndexRoute,
}

const AuthedSuperAdminRouteWithChildren =
  AuthedSuperAdminRoute._addFileChildren(AuthedSuperAdminRouteChildren)

interface AuthedRouteChildren {
  AuthedOrgSlugRoute: typeof AuthedOrgSlugRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedSuperAdminRoute: typeof AuthedSuperAdminRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgSlugRoute: AuthedOrgSlugRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedSuperAdminRoute: AuthedSuperAdminRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
